language: java

sudo: false

# No much sense in keeping jdbi artifacts cached
before_cache:
  rm -rf $HOME/.m2/repository/org/jdbi

cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
  - ./ci-pre-install.sh

install:
  - ./ci-install.sh

matrix:
  include:
    - env:
        - TESTS=Y
      script:
        - ./ci-test.sh
      jdk: oraclejdk8
    - env:
        - TESTS=Y
      script:
        - ./ci-test.sh
      jdk: oraclejdk9
    - env:
        - DOCUMENTATION=Y
      script:
        - ./ci-doc.sh
      jdk: oraclejdk8
    - env:
        - CODE_STYLE=Y
      script:
        - ./ci-code-style.sh
      jdk: oraclejdk8
